### ISSUE TITLE
Fix chat form to show 'Send' button?

### ISSUE THREAD

**Issue by ashedold** [bcruddy/tumbo#12]
Intended to be hidden?

**Comment by bcruddy** [comment]
Doesn't actually exist. This is an easy one for you to add though.

Read the [bootstrap docs](http://getbootstrap.com/css/#forms) on forms, the "inline form" with the "transfer cash" button is ideal. Instead of a suffix and prefix on the input element itself, make the suffix the button. It only needs `type="submit"`.

Then once it works, [submit a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by ashedold** [comment]
i was messing with the views/index last night and was tinkering with the form field(?) where you enter text into the chat. just resizing stuff really... anyhow - i changed something on the <button>/Send/</button> or whatever and a cyan colored button with "Send" showed up. but i guess it is meant to be hidden? Anywho - i'll tinker with it tonight.
